Aspun.Web/Controllers/BusinessUnitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Aspun.Core.Contracts;
using Aspun.Core.Model;
using Aspun.Web.ViewModels;
using Aspun.Web.AppCode.Mvc;
using Aspun.Core.Services;

namespace Aspun.Web.Controllers
{
    [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
    public class BusinessUnitController : ControllerBase
    {
        private BusinessUnitService _service;
        private UserService _userService;

        public BusinessUnitController(IAspunUow uow)
            : base(uow)
        {
            _service = new BusinessUnitService(uow);
            _userService = new UserService(uow);
        }

        [CustomAuthorizeAttribute(RequiredBusinessUnitManagementPermission = Permission3.View)]
        public ActionResult Index()
        {
            IEnumerable<BusinessUnit> bunits = Uow.BusinessUnits.GetAllNotDeleted();

            BusinessUnitListEditModel listEditModel = new BusinessUnitListEditModel(bunits);

            return View(listEditModel);
        }


        [ActionName("Index")]
        [HttpPost]
        [CustomAuthorizeAttribute(RequiredBusinessUnitManagementPermission = Permission3.All)]
        [MultiButton(RegexFormKey = "^remove\\d+$")]
        public ActionResult Index_RemoveItem(BusinessUnitListEditModel model, FormCollection form)
        {
            string res = (from item in form.AllKeys
                          where item.StartsWith("remove")
                          select item).FirstOrDefault();

            if (res != null)
            {
                // Post command to remove an item
                int index = Int32.Parse(res.Substring(6));
                model.Items.RemoveAt(index);

                // Очистить ModelState иначе список возьмется из него
                ModelState.Clear();
            }

            return View(model);
        }

        [ActionName("Index")]
        [HttpPost]
        [CustomAuthorizeAttribute(RequiredBusinessUnitManagementPermission = Permission3.All)]
        [MultiButton(MatchFormKey = "addItem")]
        public ActionResult Index_AddItem(BusinessUnitListEditModel model, FormCollection form)
        {
            var newItem = new BusinessUnitEditModel(new BusinessUnit());
            model.Items.Add(newItem);

            return View(model);
        }

        [ActionName("Index")]
        [HttpPost]
        [CustomAuthorizeAttribute(RequiredBusinessUnitManagementPermission = Permission3.All)]
        [MultiButton(MatchFormKey = "buttonSave")]
        public ActionResult Index_Save(BusinessUnitListEditModel model, FormCollection form)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            List<BusinessUnit> newList = new List<BusinessUnit>();
            model.UpdateEntity(newList);

            _service.UpdateList(newList);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult GetNewBusinessUnitItem(int index)
        {
            var model = new BusinessUnitEditModel();
            ViewData["Index"] = index;

            return PartialView("EditorTemplates/BusinessUnitEditModel", model);
        }

        /// <summary>
        /// Переопределенный метод для загрузки в модели общих данных
        /// </summary>
        /// <param name="filterContext"></param>
        protected override void OnResultExecuting(ResultExecutingContext filterContext)
        {
            base.OnResultExecuting(filterContext);

            // Дополнить модель правами пользователя
            if (filterContext.Controller.ViewData.Model is ViewModels.BusinessUnitListEditModel)
            {
                User user = _userService.GetByLogin(HttpContext.User.Identity.Name);

                var model = (ViewModels.BusinessUnitListEditModel)filterContext.Controller.ViewData.Model;

                model.IsCreateEnabled = user.PermissionSet.BusinessUnitManagementPermission >= Permission3.All;
                model.IsSaveEnabled = user.PermissionSet.BusinessUnitManagementPermission >= Permission3.All;
                model.IsDeleteEnabled = user.PermissionSet.BusinessUnitManagementPermission >= Permission3.All;
            }
            else if (filterContext.Controller.ViewData.Model is ViewModels.BusinessUnitEditModel)
            {
                User user = _userService.GetByLogin(HttpContext.User.Identity.Name);

                ViewData["isDeleteEnabled"] = user.PermissionSet.BusinessUnitManagementPermission >= Permission3.All;
                ViewData["isEditEnabled"] = user.PermissionSet.BusinessUnitManagementPermission >= Permission3.All;
            }
        }
    }
}

Aspun.Web/Views/BusinessUnit/Index.cshtml
@model Aspun.Web.ViewModels.BusinessUnitListEditModel

@{
    ViewBag.Title = "Предприятия";
}

@section Scripts {

<script type="text/javascript">

    // Функция, описывающая объект для формы Электрооборудования
    function BusinessUnitViewType() {

        var self = this; // Для обработчиков событий
        this.containerId = "businessunit-container";
        this.formId = "formBusinessUnit";
        this.rowSelector = ".businessUnitRow";
        this.numberContainerSelector = ".orderNumber";
        this.urlNewUnit = "BusinessUnit/GetNewBusinessUnitItem";
        this.addButtonId = "btnAddItem";
        this.removeButtonSelector = ".removeItem";

        // Обработчик события нажатия на кнопку добавления нового элемента
        this.addItem_onClick = function () {
            self.addItem();
            return false;
        }

        this.removeItem_onClick = function () {
            self.removeItem(this); // передаем button input в качестве параметра
            return false;
        }
    }

    // Унаследоваться от базового представления
    extend(BusinessUnitViewType, app.DynamicListView);

    // Переопределить функции

    BusinessUnitViewType.prototype.base_onLoad = app.DynamicListView.prototype.onLoad;
    BusinessUnitViewType.prototype.onLoad = function () {
        this.base_onLoad();

    };

    BusinessUnitViewType.prototype.base_onUnload = app.DynamicListView.prototype.onUnload;
    BusinessUnitViewType.prototype.onUnload = function () {
    };

    // Инициализует элементы формы при загрузке
    BusinessUnitViewType.prototype.base_initControls = app.DynamicListView.prototype.initControls;
    BusinessUnitViewType.prototype.initControls = function (container) {

        this.base_initControls(container);

        if (typeof (container) == 'undefined' || container == null) {
            $("#" + this.addButtonId).click(this.addItem_onClick);
        }

        if (typeof (container) !== 'undefined' && container != null) {
            $(this.removeButtonSelector, container).click(this.removeItem_onClick);
        }
        else {
            $(this.removeButtonSelector, "#" + this.containerId).click(this.removeItem_onClick);
        }
    };

    // Фукнция вызываемая перед отправкой запроса на добавление элемента
    BusinessUnitViewType.prototype.base_beforeRequestAddItem = app.DynamicListView.prototype.beforeRequestAddItem;
    BusinessUnitViewType.prototype.beforeRequestAddItem = function () {
        this.base_beforeRequestAddItem();
        $("#" + this.addButtonId).attr('disabled', 'disabled');
    };

    // Функция, вызываемы после выполнения запроса на добавление элемента
    BusinessUnitViewType.prototype.base_afterRequestAddItem = app.DynamicListView.prototype.afterRequestAddItem;
    BusinessUnitViewType.prototype.afterRequestAddItem = function () {
        this.base_afterRequestAddItem();
        $("#" + this.addButtonId).removeAttr('disabled');
    };

    var BusinessUnitView = new BusinessUnitViewType();

</script>

<script type="text/javascript">
    $(document).ready(function () {
        BusinessUnitView.onLoad();
    });

    $(window).unload(function () {
        BusinessUnitView.onUnload();
    });   
</script>
       
}


<h2>Предприятия</h2>

@using (Html.BeginForm("Index", "BusinessUnit", FormMethod.Post, new { id = "formBusinessUnit" }))
{
    @Html.ValidationSummary(false, Aspun.Web.Resources.ValidationStrings.SomeFieldIsNotValid, new { id = "businessunit-validation" })
    
    <table id="businessunit-container">
        <thead>
            <tr>
                <th></th>
                <th>Наименование
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Items.Count; i++)
            {
                @Html.EditorFor(model => model.Items[i], new { index = i, isDeleteEnabled = Model.IsDeleteEnabled, isEditEnabled = Model.IsSaveEnabled })
            }
        </tbody>

    </table>

    <p>
        @if(Model.IsCreateEnabled) {
            <input id="btnAddItem" type="submit" name="addItem" value="Добавить" title="Добавить" class="btn"/>
        }
    </p>    
    
    <p>
        @if(Model.IsSaveEnabled) {
            <input type="submit" name="buttonSave" value="Сохранить" class="btn"/>
        }
        @Html.ActionLink("Отмена", "Index", "Home", null, new { @class = "btn" })
    </p>
}