Aspun.Web/Controllers/ViolationTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Aspun.Core.Contracts;
using Aspun.Core.Model;
using Aspun.Web.ViewModels;
using Aspun.Web.AppCode.Mvc;
using Aspun.Core.Services;

namespace Aspun.Web.Controllers
{
    [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
    public class ViolationTypeController : ControllerBase
    {
        private ViolationTypeService _service;
        private UserService _userService;

        public ViolationTypeController(IAspunUow uow)
            : base(uow)
        {
            _service = new ViolationTypeService(uow);
            _userService = new UserService(uow);
        }

        //
        // GET: /ViolationType/
        [CustomAuthorizeAttribute(RequiredViolationTypeManagementPermission = Permission3.View)]
        public ActionResult Index()
        {
            IEnumerable<ViolationType> vtypes = Uow.ViolationTypes.GetAll();

            ViolationTypeListEditModel listEditModel = new ViolationTypeListEditModel(vtypes);

            return View(listEditModel);
        }


        [ActionName("Index")]
        [HttpPost]
        [MultiButton(RegexFormKey = "^remove\\d+$")]
        [CustomAuthorizeAttribute(RequiredViolationTypeManagementPermission = Permission3.All)]
        public ActionResult Index_RemoveItem(ViolationTypeListEditModel model, FormCollection form)
        {
            string res = (from item in form.AllKeys
                          where item.StartsWith("remove")
                          select item).FirstOrDefault();

            if (res != null)
            {
                // Post command to remove an item
                int index = Int32.Parse(res.Substring(6));
                model.Items.RemoveAt(index);

                // Очистить ModelState иначе список возьмется из него
                ModelState.Clear();
            }

            return View(model);
        }

        [ActionName("Index")]
        [HttpPost]
        [MultiButton(MatchFormKey = "addItem")]
        [CustomAuthorizeAttribute(RequiredViolationTypeManagementPermission = Permission3.All)]
        public ActionResult Index_AddItem(ViolationTypeListEditModel model, FormCollection form)
        {
            var newItem = new ViolationTypeEditModel(new ViolationType());
            model.Items.Add(newItem);

            return View(model);
        }

        [ActionName("Index")]
        [HttpPost]
        [MultiButton(MatchFormKey = "buttonSave")]
        [CustomAuthorizeAttribute(RequiredViolationTypeManagementPermission = Permission3.All)]
        public ActionResult Index_Save(ViolationTypeListEditModel model, FormCollection form)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            List<ViolationType> newList = new List<ViolationType>();
            model.UpdateEntity(newList);

            _service.UpdateList(newList);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult GetNewViolationTypeItem(int index)
        {
            var model = new ViolationTypeEditModel();
            ViewData["Index"] = index;

            return PartialView("EditorTemplates/ViolationTypeEditModel", model);
        }

        /// <summary>
        /// Переопределенный метод для загрузки в модели общих данных
        /// </summary>
        /// <param name="filterContext"></param>
        protected override void OnResultExecuting(ResultExecutingContext filterContext)
        {
            base.OnResultExecuting(filterContext);

            // Дополнить модель правами пользователя
            if (filterContext.Controller.ViewData.Model is ViewModels.ViolationTypeListEditModel)
            {
                User user = _userService.GetByLogin(HttpContext.User.Identity.Name);

                var model = (ViewModels.ViolationTypeListEditModel)filterContext.Controller.ViewData.Model;

                model.IsCreateEnabled = user.PermissionSet.ViolationTypeManagementPermission >= Permission3.All;
                model.IsSaveEnabled = user.PermissionSet.ViolationTypeManagementPermission >= Permission3.All;
                model.IsDeleteEnabled = user.PermissionSet.ViolationTypeManagementPermission >= Permission3.All;
            }
            else if (filterContext.Controller.ViewData.Model is ViewModels.ViolationTypeEditModel)
            {
                User user = _userService.GetByLogin(HttpContext.User.Identity.Name);

                ViewData["isDeleteEnabled"] = user.PermissionSet.ViolationTypeManagementPermission >= Permission3.All;
                ViewData["isEditEnabled"] = user.PermissionSet.ViolationTypeManagementPermission >= Permission3.All;
            }
        }
    }
}

Aspun.Web/Views/ViolationType/Index.cshtml
@model Aspun.Web.ViewModels.ViolationTypeListEditModel

@{
    ViewBag.Title = "Типы нарушений";
}

@section Scripts {

<script type="text/javascript">

    // Функция, описывающая объект для формы
    function ViolationTypeViewType() {

        var self = this; // Для обработчиков событий
        this.containerId = "violationtype-container";
        this.formId = "formViolationType";
        this.rowSelector = ".violationTypeRow";
        this.numberContainerSelector = ".orderNumber";
        this.urlNewUnit = "ViolationType/GetNewViolationTypeItem";
        this.addButtonId = "btnAddItem";
        this.removeButtonSelector = ".removeItem";

        // Обработчик события нажатия на кнопку добавления нового элемента
        this.addItem_onClick = function () {
            self.addItem();
            return false;
        }

        this.removeItem_onClick = function () {
            self.removeItem(this); // передаем button input в качестве параметра
            return false;
        }
    }

    // Унаследоваться от базового представления
    extend(ViolationTypeViewType, app.DynamicListView);

    // Переопределить функции

    ViolationTypeViewType.prototype.base_onLoad = app.DynamicListView.prototype.onLoad;
    ViolationTypeViewType.prototype.onLoad = function () {
        this.base_onLoad();

    };

    ViolationTypeViewType.prototype.base_onUnload = app.DynamicListView.prototype.onUnload;
    ViolationTypeViewType.prototype.onUnload = function () {
    };

    // Инициализует элементы формы при загрузке
    ViolationTypeViewType.prototype.base_initControls = app.DynamicListView.prototype.initControls;
    ViolationTypeViewType.prototype.initControls = function (container) {

        this.base_initControls(container);

        if (typeof (container) == 'undefined' || container == null) {
            $("#" + this.addButtonId).click(this.addItem_onClick);
        }

        if (typeof (container) !== 'undefined' && container != null) {
            $(this.removeButtonSelector, container).click(this.removeItem_onClick);
        }
        else {
            $(this.removeButtonSelector, "#" + this.containerId).click(this.removeItem_onClick);
        }
    };

    // Фукнция вызываемая перед отправкой запроса на добавление элемента
    ViolationTypeViewType.prototype.base_beforeRequestAddItem = app.DynamicListView.prototype.beforeRequestAddItem;
    ViolationTypeViewType.prototype.beforeRequestAddItem = function () {
        this.base_beforeRequestAddItem();
        $("#" + this.addButtonId).attr('disabled', 'disabled');
    };

    // Функция, вызываемы после выполнения запроса на добавление элемента
    ViolationTypeViewType.prototype.base_afterRequestAddItem = app.DynamicListView.prototype.afterRequestAddItem;
    ViolationTypeViewType.prototype.afterRequestAddItem = function () {
        this.base_afterRequestAddItem();
        $("#" + this.addButtonId).removeAttr('disabled');
    };

    var ViolationTypeView = new ViolationTypeViewType();


</script>

<script type="text/javascript">
    $(document).ready(function () {
        ViolationTypeView.onLoad();
    });

    $(window).unload(function () {
        ViolationTypeView.onUnload();
    });   
</script>
       
}

<h2>Типы нарушений</h2>

@using (Html.BeginForm("Index", "ViolationType", FormMethod.Post, new { id = "formViolationType" }))
{
    @Html.ValidationSummary(false, Aspun.Web.Resources.ValidationStrings.SomeFieldIsNotValid, new { id = "violationtype-validation" })
    
    <table id="violationtype-container" >
        <thead>

            <tr>
                <th></th>
                <th>Шифр нарушения
                </th>
                <th>Описание
                </th>
                <th>Пункт правил
                </th>
                <th></th>
            </tr>

        </thead>
        <tbody>
            @for (int i = 0; i < Model.Items.Count; i++)
            {
                @Html.EditorFor(model => model.Items[i], new { index = i, isDeleteEnabled = Model.IsDeleteEnabled, isEditEnabled = Model.IsSaveEnabled  })
            }
        </tbody>

    </table>

    <p>
        @if(Model.IsCreateEnabled) {
            <input id="btnAddItem" type="submit" name="addItem" value="Добавить" title="Добавить новый тип" class="btn" />
        }
    </p>    
    
    <p>
        @if(Model.IsSaveEnabled) {
            <input type="submit" name="buttonSave" value="Сохранить" class="btn" />
        }
        @Html.ActionLink("Отмена", "Index", "Home", null, new { @class = "btn" })
    </p>
}