Aspun.Web/ViewModels/Violation/PagedViolationsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Aspun.Web.ViewModels
{
    public class PagedViolationsModel
    {
        public int PageSize { get; set; }
        public int PageNumber { get; set; }
        public int TotalRows { get; set; }
        public IList<ViolationBriefModel> Violations { get; set; }
        public bool UserCanEdit { get; set; }
        public bool IsCreateEnabled { get; set; }

        public PagedViolationsModel()
        {
            PageSize = 0;
            PageNumber = 0;
            TotalRows = 0;
            Violations = new List<ViolationBriefModel>();
            UserCanEdit = false;
        }
    }
}

Aspun.Web/ViewModels/Violation/ViolationBaseModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Aspun.Core.Model;
using Aspun.Core.Services;
using Aspun.Web.AppCode.Mvc;
using Aspun.Web.AppCode;
using System.ComponentModel.DataAnnotations;

namespace Aspun.Web.ViewModels
{
    public class ViolationBaseModel
    {
        public virtual int ViolationId { get; set; }



        [UIHint("DateTimePicker")]
        //[DataType(DataType.Date, ErrorMessage = "Невозможно распознать указанную дату")]
        [DatePickerValidatorAttribute(ErrorMessageResourceName = "DateIsNotValid", ErrorMessageResourceType = typeof(Resources.ValidationStrings))]
        [LocalizedDisplayNameAttribute("ViolationDate", NameResourceType = typeof(Resources.Names))]
        [Required(ErrorMessageResourceType = typeof(Resources.ValidationStrings), ErrorMessageResourceName = "FieldIsRequired")]
        public virtual String DateString { get; set; }

        [LocalizedDisplayNameAttribute("ViolationDescription", NameResourceType = typeof(Resources.Names))]
        [MaxLength(Violation.MAXL_DESCRIPTION, ErrorMessageResourceName = "MaxLengthExceeded", ErrorMessageResourceType = typeof(Resources.ValidationStrings))]
        public string Description { get; set; }

        public ViolationBaseModel ()
	    {
                
	    }

        public ViolationBaseModel(Violation entity)
            : this()
        {
            ConvertEntity(entity);
        }

        public virtual void UpdateEntity(Violation entity)
        {
            DateTime date;


            entity.Date = (ConvertHelper.TryParseDateTime(DateString, out date)) ? date : DateTime.Now;
            entity.Description = Description;
        }

        protected virtual void ConvertEntity(Violation entity)
        {
            ViolationId = entity.ViolationId;

            DateString = ConvertHelper.ToString(entity.Date);
            Description = entity.Description;
        }

        public virtual IEnumerable<RuleViolation> GetRuleViolations(ViolationService violationService)
        {
            List<RuleViolation> rv = new List<RuleViolation>();

            return rv;
        }
    }
}

Aspun.Web/ViewModels/Violation/ViolationBriefModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Aspun.Core.Model;

namespace Aspun.Web.ViewModels
{
    public class ViolationBriefModel
    {
        public int ViolationId { get; set; }

        public string Number { get; set; }

        public DateTime Date { get; set; }

        public string BusinessUnitName { get; set; }

        public string EmployeeFIO { get; set; }

        public string EmployeeNumber { get; set; }

        public string EmployeePosition { get; set; }

        public string EmployeeUnit { get; set; }

        public string ViolationTypeDescription { get; set; }

        public ViolationBriefModel()
        {
            
        }

        public ViolationBriefModel(Violation entity)
            : this()
        {
            ConvertEntity(entity);
        }

        private void ConvertEntity(Violation entity)
        {
            ViolationId = entity.ViolationId;
            Number = entity.Number;
            Date = entity.Date;
            BusinessUnitName = entity.BusinessUnitName;
            EmployeeFIO = entity.EmployeeFIO;
            EmployeeNumber = entity.EmployeeNumber;
            EmployeePosition = entity.EmployeePosition;
            EmployeeUnit = entity.EmployeeUnit;
            ViolationTypeDescription = entity.ViolationTypeDescription;
        }
    }
}

Aspun.Web/ViewModels/Violation/ViolationDetailsModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Aspun.Core.Model;
using Aspun.Core.Services;
using Aspun.Web.AppCode;
using Aspun.Web.AppCode.Mvc;

namespace Aspun.Web.ViewModels
{
    public class ViolationDetailsModel
    {
        public int ViolationId { get; set; }

        [LocalizedDisplayNameAttribute("ViolationNumber", NameResourceType = typeof(Resources.Names))]
        public string Number { get; set; }

        [LocalizedDisplayNameAttribute("ViolationDate", NameResourceType = typeof(Resources.Names))]
        public String DateString { get; set; }

        [LocalizedDisplayNameAttribute("BusinessUnitName", NameResourceType = typeof(Resources.Names))]
        public string BusinessUnitName { get; set; }

        [LocalizedDisplayNameAttribute("EmployeeFIO", NameResourceType = typeof(Resources.Names))]
        public string EmployeeFIO { get; set; }

        [LocalizedDisplayNameAttribute("EmployeeNumber", NameResourceType = typeof(Resources.Names))]
        public string EmployeeNumber { get; set; }

        [LocalizedDisplayNameAttribute("EmployeePosition", NameResourceType = typeof(Resources.Names))]
        public string EmployeePosition { get; set; }

        [LocalizedDisplayNameAttribute("ViolationTypeCode", NameResourceType = typeof(Resources.Names))]
        public string ViolationTypeCode { get; set; }

        [LocalizedDisplayNameAttribute("ViolationTypeDescription", NameResourceType = typeof(Resources.Names))]
        public string ViolationTypeDescription { get; set; }

        [LocalizedDisplayNameAttribute("ViolationTypePar", NameResourceType = typeof(Resources.Names))]
        public string ViolationTypePar { get; set; }

        [LocalizedDisplayNameAttribute("ViolationDescription", NameResourceType = typeof(Resources.Names))]
        public string Description { get; set; }

        [LocalizedDisplayNameAttribute("ViolationCreatorUserName", NameResourceType = typeof(Resources.Names))]
        public string CreatorUserName { get; set; }

        public ViolationDetailsModel()
        {

        }

        public ViolationDetailsModel(Violation entity)
        {
            ConvertEntity(entity);
        }


        protected void ConvertEntity(Violation entity)
        {
            ViolationId = entity.ViolationId;
            Number = entity.Number;
            DateString = ConvertHelper.ToString(entity.Date);
            BusinessUnitName = entity.BusinessUnitName;
            EmployeeFIO = entity.EmployeeFIO;
            EmployeeNumber = entity.EmployeeNumber;
            EmployeePosition = entity.EmployeePosition;
            ViolationTypeDescription = entity.ViolationTypeDescription;
            ViolationTypePar = entity.ViolationTypePar;
            ViolationTypeCode = entity.ViolationTypeCode;
            Description = entity.Description;
            CreatorUserName = entity.CreatorUserName;
        }
    }
}

Aspun.Web/Controllers/ViolationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Aspun.Web.AppCode;
using Aspun.Web.AppCode.Mvc;
using Aspun.Core.Contracts;
using Aspun.Core.Model;
using Aspun.Core.Services;
using Aspun.Web.ViewModels;
using Aspun.Common;

namespace Aspun.Web.Controllers
{
    [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
    public class ViolationController : ControllerBase
    {
        private UserService _userService;
        private ViolationService _violationService;
        private ViolationTypeService _violationTypeService;
        private EmployeeService _employeeService;
        private BusinessUnitService _businesUnitService;

        private const int MAX_SEARCH_COUNT = 15;
        private readonly string[] SEARCH_FIELDS = new string[] { "FIO", "Number", "Position" };

        public ViolationController(IAspunUow uow)
            : base(uow)
        {
            _userService = new UserService(uow);
            _violationService = new ViolationService(uow);
            _violationTypeService = new ViolationTypeService(uow);
            _employeeService = new EmployeeService(uow);
            _businesUnitService = new BusinessUnitService(uow);
        }

        [CustomAuthorizeAttribute(RequiredViolationManagementPermission = Permission4.View)]
        public ActionResult Index(int? page, string sort, string sortdir /* ASC/DESC */)
        {
            // Список сотрудников необходимо отфильтровать по БЕ, к которым у пользователя есть доступ
            User user = _userService.GetByLogin(HttpContext.User.Identity.Name);

            // Извлекаем параметры запроса
            string sortField = sort;
            bool asc = "ASC".Equals(sortdir, StringComparison.InvariantCultureIgnoreCase) ? true : false;

            // Заполняем модель
            PagedViolationsModel model = new PagedViolationsModel();
            model.UserCanEdit = user.PermissionSet.ViolationManagementPermission >= Permission4.InsertUpdate;
            model.IsCreateEnabled = user.PermissionSet.ViolationManagementPermission >= Permission4.InsertUpdate;

            model.PageSize = 15;
            model.PageNumber = page.HasValue ? page.Value : 1;
            
            int totalRows = 0;
            IEnumerable<Violation> violations;

            if (user.HasAccessToAllBusinessUnits)
            {
                // Выбрать всех сотрудников
                violations = _violationService.GetViolations(model.PageSize, model.PageNumber, sortField, asc, out totalRows);
            }
            else
            {
                if (user.BusinessUnits == null || user.BusinessUnits.Count == 0)
                {
                    violations = new List<Violation>();
                }
                else
                {
                    IEnumerable<string> buNames = user.BusinessUnits.Select(bu => bu.Name);
                    violations = _violationService.GetViolations(buNames, model.PageSize, model.PageNumber, sortField, asc, out totalRows);
                }
            }

            model.TotalRows = totalRows;
            //model.Violations = violations;
            foreach (Violation v in violations)
            {
                model.Violations.Add(new ViolationBriefModel(v));
            }

            return View(model);
        }

        [CustomAuthorizeAttribute(RequiredViolationManagementPermission = Permission4.InsertUpdate)]
        public ActionResult Create()
        {
            ViolationCreateModel model = new ViolationCreateModel();

            // Initialize default values
            model.DateString = DateTime.Now.ToShortDateString();

            return View(model);
        }

        [HttpPost]
        [CustomAuthorizeAttribute(RequiredViolationManagementPermission = Permission4.InsertUpdate)]
        public ActionResult Create(ViolationCreateModel model, FormCollection collection)
        {
            ModelState.AddRuleViolations(model.GetRuleViolations(_violationService));

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // Загрузить по ViolationId описание нарушения и параграф нарушения
            ViolationType selectedViolationType = _violationTypeService.GetById(model.SelectedViolationId);
            if (selectedViolationType == null)
            {
                ModelState.AddModelError("SelectedViolationId", "Выбран недействительный тип нарушения.");
                return View(model);
            }

            BusinessUnit selectedBusinessUnit = _businesUnitService.GetById(model.SelectedBusinessUnitId);
            if (selectedBusinessUnit == null)
            {
                ModelState.AddModelError("SelectedBusinessUnitId", "Выбрано недействительное предприятие.");
                return View(model);
            }

            User user = _userService.GetByLogin(HttpContext.User.Identity.Name);

            //// Загрузить по EmployeeId аттрибуты сотрудника
            //Employee employee = model.SelectedEmployeeId.HasValue ? _employeeService.GetById(model.SelectedEmployeeId.Value) : null;
            //if (employee == null)
            //{
            //    ModelState.AddModelError("SelectedEmployeeId", "Не выбран сотрудник.");
            //    return View(model);
            //}

            //// Проверить, что совпадает выбранные Business Unit и Business Unit 
            //if (!String.Equals(employee.BusinessUnit, model.BusinessUnitName, StringComparison.InvariantCultureIgnoreCase))
            //{
            //    ModelState.AddModelError("SelectedEmployeeId", "Бизнес еденица в которой состоит сотрудник не совпадает с выбранной.");
            //    return View(model);
            //}

            // Проверить, что пользователь имеет доступ к Buinsees Unit
            if (!UserHasAccessToBusinessUnit(user, selectedBusinessUnit.Name /*model.BusinessUnitName*/))
            {
                throw new InvalidOperationException("Пользователь не имеет доступа к указанной бизнес-единице.");
            }

            Violation violation = new Violation();

            model.UpdateEntity(violation);

            // Заполнить дополнительные поля, которые не входят в модель
            violation.CreatorUserName = HttpContext.User.Identity.Name;
            violation.ViolationTypeDescription = selectedViolationType.Description;
            violation.ViolationTypePar = selectedViolationType.RegulationsPar;
            violation.ViolationTypeCode = selectedViolationType.Code;
            violation.BusinessUnitName = selectedBusinessUnit.Name;
            violation.Prefix = selectedBusinessUnit.Prefix;

            _violationService.Create(violation);
            
            // Метод Create обновил индекс (номер) нарушения так что его можно использовать


            //return RedirectToAction("Index");

            return View("Created", violation);
        }

        //[CustomAuthorizeAttribute(RequiredViolationManagementPermission = Permission4.InsertUpdate)]
        //public ActionResult Created()
        //{
        //}

        [CustomAuthorizeAttribute(RequiredViolationManagementPermission = Permission4.InsertUpdate)]
        public ActionResult Edit(int id)
        {
            Violation violation = _violationService.GetById(id);

            if (violation == null)
            {
                return NotFound();
            }
            User user = _userService.GetByLogin(HttpContext.User.Identity.Name);

            ViolationEditModel model = new ViolationEditModel(violation);
            model.IsDeleteEnabled = (user.PermissionSet.ViolationManagementPermission >= Permission4.All);

            return View(model);
        }

        [HttpPost]
        [CustomAuthorizeAttribute(RequiredViolationManagementPermission = Permission4.InsertUpdate)]
        public ActionResult Edit(ViolationEditModel model, int id, FormCollection collection)
        {
            User user = _userService.GetByLogin(HttpContext.User.Identity.Name);
            model.IsDeleteEnabled = (user.PermissionSet.ViolationManagementPermission >= Permission4.All);

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // Проверить что пользователь может редактировать нарушения из указанной БЕ

            if (!UserHasAccessToBusinessUnit(user, model.BusinessUnitName))
            {
                throw new InvalidOperationException("Пользователь не имеет доступа к указанной бизнес-единице.");
            }

            Violation violation = _violationService.GetById(id);

            if (violation == null)
            {
                return NotFound();
            }

            model.UpdateEntity(violation);

            _violationService.Update(violation);

            return RedirectToAction("Index");
        }

        [CustomAuthorizeAttribute(RequiredViolationManagementPermission = Permission4.View)]
        public ActionResult Details(int id)
        {
            Violation violation = _violationService.GetById(id);

            if (violation == null)
            {
                return NotFound();
            }

            // Проверить что пользователь имеет доступ к этой БЕ
            User user = _userService.GetByLogin(HttpContext.User.Identity.Name);

            if (!UserHasAccessToBusinessUnit(user, violation.BusinessUnitName))
            {
                throw new InvalidOperationException("Пользователь не имеет доступа к указанной бизнес-единице.");
            }

            ViolationDetailsModel model = new ViolationDetailsModel(violation);

            return View(model);
        }

        [CustomAuthorizeAttribute(RequiredViolationManagementPermission = Permission4.All)]
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        [HttpPost]
        [CustomAuthorizeAttribute(RequiredViolationManagementPermission = Permission4.All)]

Aspun.Web/Views/Violation/Create.cshtml
@model Aspun.Web.ViewModels.ViolationCreateModel

@{
    ViewBag.Title = "Ввод нарушения";
}

@section Scripts {

    <script type="text/javascript">

        function ViolationViewType() {

            var self = this; // Для обработчиков событий

            this.formSelector = "#formViolation";
            //this.selectedEmplId = $("#SelectedEmployeeId").val();
            //this.selectedEmplText = $("#EmployeeCombinedText").val();

            this.autocomplete_source = function (request, response) {
                $.ajax({
                    url: this.element.attr("data-source-url"),
                    dataType: "json",
                    data: {
                        term: request.term
                    },
                    success: function (data) {
                        response(data);
                    }
                });
            };

            this.autocomplete_select = function (event, ui) {

                if (ui.item) {
                    // selected
                    //self.selectedEmplId = ui.item.id;
                    //self.selectedEmplText = ui.item.value;

                    //$("#SelectedEmployee").val(ui.item.fio);
                    ui.item.value = ui.item.fio;
                    $("#EmployeeNumber").val(ui.item.number);
                    $("#EmployeePosition").val(ui.item.position);
                    $("#EmployeeUnit").val(ui.item.unit);

                    // Выбрать соответствующий БЕ
                    // ...  сначала выбрать value по тексту
                    var buValue = $('select#SelectedBusinessUnitId option').filter(function ()
                    {
                        return $(this).html() == ui.item.bu;
                    }).val();

                    $('select#SelectedBusinessUnitId').val(buValue);
                }

                return true;
            };

            //this.onSubmit = function () {
            //    // Перед отправкой данных на сервер проверить, что введенный Employee (в input'е)
            //    // совпадает с тем что выбрано из autocomplete
            //    var inputText = $("#EmployeeCombinedText").val();

            //    if (inputText != self.selectedEmplText) {
            //        // Показать валидационную ошибку, что сотрудник выбран неправильный (не из существующего списка)
            //        $("#SelectedEmployeeId").val('');
            //        $("#SelectedEmployeeId").valid();
            //        return false;
            //    }
            //    else {
            //        // сохранить Id выбранного Employee в поле, чтобы передать на сервер
            //        $("#SelectedEmployeeId").val(self.selectedEmplId);
            //    }
            //};
        }

        // Унаследоваться от базового представления
        extend(ViolationViewType, app.ViewBase);

        // Переопределить функции

        ViolationViewType.prototype.base_onLoad = app.ViewBase.prototype.onLoad;
        ViolationViewType.prototype.onLoad = function () {
            this.base_onLoad();

            this.initControls();
        };

        ViolationViewType.prototype.base_onUnload = app.ViewBase.prototype.onUnload;
        ViolationViewType.prototype.onUnload = function () {
        };

        // Инициализует элементы формы при загрузке
        ViolationViewType.prototype.base_initControls = app.ViewBase.prototype.initControls;
        ViolationViewType.prototype.initControls = function (container) {

            this.base_initControls(container);

            $("input.employeecomplete", container).autocomplete({
                source: this.autocomplete_source,
                select: this.autocomplete_select
                //change: function (event, ui) { alert('changed');}
            });

            //$(this.formSelector).submit(this.onSubmit);

        };

        var ViolationView = new ViolationViewType();
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            ViolationView.onLoad();
        });

        $(window).unload(function () {
            ViolationView.onUnload();
        });
    </script>

    }

<h2>Ввод нарушения</h2>

@using (Html.BeginForm("Create", "Violation", FormMethod.Post, new { id = "formViolation" }))
{
    @Html.ValidationSummary(false, Aspun.Web.Resources.ValidationStrings.SomeFieldIsNotValid, new { id = "violationcreate-validation" })

    @Html.HiddenFor(model => model.ViolationId)

    <table class="table-fluid">
@*        <tr>
            <td>
                @Html.LabelFor(model => model.Number)
            </td>
            <td>
                @Html.EditorFor(model => model.Number)
            </td>
            <td>
                @Html.ValidationMessageFor(model => model.Number)
            </td>
        </tr>*@
        <tr>
            <td>
                @Html.LabelFor(model => model.DateString)
            </td>
            <td>
                @Html.EditorFor(model => model.DateString)
            </td>
            <td>
                @Html.ValidationMessageFor(model => model.DateString)
            </td>
        </tr>
@*        <tr>
            <td>
                @Html.LabelFor(model => model.BusinessUnitName)
            </td>
            <td>
                @Html.DropDownListFor(model => model.BusinessUnitName, Model.BusinessUnitList, new { @class="x2" })
            </td>
            <td>
                @Html.ValidationMessageFor(model => model.BusinessUnitName)
            </td>
        </tr>*@
        <tr>
            <td>
                @Html.LabelFor(model => model.SelectedBusinessUnitId)
            </td>
            <td>
                @Html.DropDownListFor(model => model.SelectedBusinessUnitId, Model.BusinessUnitList, new { @class="x2" })
            </td>
            <td>
                @Html.ValidationMessageFor(model => model.SelectedBusinessUnitId)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.SelectedEmployee)
            </td>
            <td>
                @Html.TextBoxFor(model => model.SelectedEmployee, new { @class = "employeecomplete x2", data_source_url = "Employees" })
            </td>
            <td>
                @Html.ValidationMessageFor(model => model.SelectedEmployee)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.EmployeeNumber)
            </td>
            <td>
                @Html.EditorFor(model => model.EmployeeNumber)
            </td>
            <td>
                @Html.ValidationMessageFor(model => model.EmployeeNumber)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.EmployeePosition)
            </td>
            <td>
                @Html.TextBoxFor(model => model.EmployeePosition, new { @class = "x2" })
            </td>
            <td>
                @Html.ValidationMessageFor(model => model.EmployeePosition)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.EmployeeUnit)
            </td>
            <td>
                @Html.TextBoxFor(model => model.EmployeeUnit, new { @class = "x2" })
            </td>
            <td>
                @Html.ValidationMessageFor(model => model.EmployeeUnit)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.SelectedViolationId)
            </td>
            <td>
                @Html.DropDownListFor(model => model.SelectedViolationId, Model.ViolationList, new { @class="x3" })
            </td>
            <td>
                @Html.ValidationMessageFor(model => model.SelectedViolationId)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.Description)
            </td>
            <td>
                @Html.TextAreaFor(model => model.Description, 5, 80, new { @class="x2" })
            </td>
            <td>
                @Html.ValidationMessageFor(model => model.Description)
            </td>
        </tr>
    </table>
    
    <p>
        <input type="submit" value="Создать" class="btn"/>
        @Html.ActionLink("Отмена", "Index", null, new { @class="btn"} )
    </p>
}

Aspun.Web/Views/Violation/Created.cshtml
@model Aspun.Core.Model.Violation

@{
    ViewBag.Title = "Нарушение добавлено";
}

<h2>Нарушение добавлено</h2>

<table class="details">
    <tr>
        <td>
            <div class="display-label">
                <span>Присвоенный номер:</span>
            </div>
        </td>
        <td>
            <div class="display-field">
                @Html.DisplayFor(model => model.Number)
            </div>
        </td>
    </tr>
</table>
<br />
<p>
    @Html.ActionLink("Добавить еще одно нарушение", "Create", null, new { })
</p>
<p>
    @Html.ActionLink("← Вернуться к списку нарушений", "Index", null, new { })
</p>

Aspun.Web/Views/Violation/Delete.cshtml
@{
    ViewBag.Title = "Удаление нарушения";
}

<h2>Удаление нарушения</h2>

<span>Подтвердите удаление нарушения</span>

<br />

@using (Html.BeginForm("Delete", "Violation", FormMethod.Post, new { id = "formDeleteViolation" }))
{
    <input type="submit" class="btn" name="delete" value="Удалить" />
    @Html.ActionLink("Отмена", "Index", null, new { @class="btn"})
}

Aspun.Web/Views/Violation/Details.cshtml
@model Aspun.Web.ViewModels.ViolationDetailsModel

@{
    ViewBag.Title = "Проосмотр нарушения";
}

<h2>Просмотр нарушения</h2>


<table class="details">
    <tr>
        <td>
            <div class="display-label">
                @Html.DisplayNameFor(model => model.Number)
            </div>
        </td>
        <td>
            <div class="display-field">
                @Html.DisplayFor(model => model.Number)
            </div>
        </td>
    </tr>
    <tr>
        <td>
            <div class="display-label">
                @Html.DisplayNameFor(model => model.DateString)
            </div>
        </td>
        <td>
            <div class="display-field">
                @Html.DisplayFor(model => model.DateString)
            </div>

        </td>
    </tr>
    <tr>
        <td>
            <div class="display-label">
                @Html.DisplayNameFor(model => model.BusinessUnitName)
            </div>

        </td>
        <td>
            <div class="display-field">
                @Html.DisplayFor(model => model.BusinessUnitName)
            </div>
        </td>
    </tr>
    <tr>
        <td>
            <div class="display-label">
                @Html.DisplayNameFor(model => model.EmployeeFIO)
            </div>
        </td>
        <td>
            <div class="display-field">
                @Html.DisplayFor(model => model.EmployeeFIO)
            </div>
        </td>
    </tr>
    <tr>
        <td>
            <div class="display-label">
                @Html.DisplayNameFor(model => model.EmployeeNumber)
            </div>
        </td>
        <td>
            <div class="display-field">
                @Html.DisplayFor(model => model.EmployeeNumber)
            </div>
        </td>
    </tr>
    <tr>
        <td>
            <div class="display-label">
                @Html.DisplayNameFor(model => model.EmployeePosition)
            </div>
        </td>
        <td>
            <div class="display-field">
                @Html.DisplayFor(model => model.EmployeePosition)
            </div>
        </td>
    </tr>
    <tr>
        <td>
            <div class="display-label">
                @Html.DisplayNameFor(model => model.ViolationTypeCode)
            </div>
        </td>
        <td>
            <div class="display-field">
                @Html.DisplayFor(model => model.ViolationTypeCode)
            </div>
        </td>
    </tr>
    <tr>
        <td>
            <div class="display-label">
                @Html.DisplayNameFor(model => model.ViolationTypeDescription)
            </div>
        </td>
        <td>
            <div class="display-field">
                @Html.DisplayFor(model => model.ViolationTypeDescription)
            </div>
        </td>
    </tr>
    <tr>
        <td>
            <div class="display-label">
                @Html.DisplayNameFor(model => model.ViolationTypePar)
            </div>
        </td>
        <td>
            <div class="display-field">
                @Html.DisplayFor(model => model.ViolationTypePar)
            </div>
        </td>
    </tr>
    <tr>
        <td>
            <div class="display-label">
                @Html.DisplayNameFor(model => model.Description)
            </div>
        </td>
        <td>
            <div class="display-field">
                @Html.DisplayFor(model => model.Description)
            </div>
        </td>
    </tr>
    <tr>
        <td>
            <div class="display-label">
                @Html.DisplayNameFor(model => model.CreatorUserName)
            </div>
        </td>
        <td>
            <div class="display-field">
                @Html.DisplayFor(model => model.CreatorUserName)
            </div>
        </td>
    </tr>
</table>
<br />
<p>
    @Html.ActionLink("← Вернуться к списку нарушений", "Index", null, new { })
</p>